server:
  port: 8001
  servlet:
    context-path: /apis

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/cube?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lhl!@#123
  redis:
    database: 4
    host: 127.0.0.1
    port: 6379
    password: lhl!@#123
    # 连接超时时间
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池的最大数据库连接数
        max-active: 50
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  servlet:
    multipart:
      # 文件上传限制最大20M
      maxFileSize: 20MB
      # 多文件上传限制最大20M
      maxRequestSize: 20MB

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: is_delete
      # 逻辑已删除
      logic-delete-value: 1
      # 逻辑未删除
      logic-not-delete-value: 0

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否使用cookie鉴权
  is-read-cookie: false
  # 是否尝试从 请求体 里读取 Token
  is-read-body: false
  # 是否在初始化配置时打印版本字符画
  is-print: false

cube:
  # 是否开启统一响应结果封装
  response:
    enable: true
  # 是否开启脱敏处理
  desensitized:
    enable: true

  storage:
    client:
      minio:
        enable: true
        endpoint: http://127.0.0.1:9000/
        serverUrl: http://127.0.0.1:9000/
        defaultBucketName: cube
        accessKey: minioadmin
        secretKey: minioadmin
      local:
        enable: false
        endpoint: http://127.0.0.1:8001/
        defaultBucketName: cube
        readBlockSize: 8092
        writeBlockSize: 2048
