server:
  port: 8001
  servlet:
    context-path: /apis

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://127.0.0.1:3306/cube?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mom!@#123

  flyway:
    # 启用或禁用 flyway
    enabled: true
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    baseline-version: 1
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: true
    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    validate-on-migrate: true

  redis:
    database: 4
    host: 127.0.0.1
    port: 6379
    password: mom!@#123
    # 连接超时时间
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池的最大数据库连接数
        max-active: 50
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  servlet:
    multipart:
      # 文件上传限制最大20M
      maxFileSize: 20MB
      # 多文件上传限制最大20M
      maxRequestSize: 20MB

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: is_delete
      # 逻辑已删除
      logic-delete-value: 1
      # 逻辑未删除
      logic-not-delete-value: 0

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 86400
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否使用cookie鉴权
  is-read-cookie: false
  # 是否尝试从 请求体 里读取 Token
  is-read-body: false
  # 是否在初始化配置时打印版本字符画
  is-print: false

cube:
  # 是否开启统一响应结果封装
  response:
    enable: true
  # 是否开启脱敏处理
  desensitized:
    enable: true
  # 是否开启数据权限限制

  storage:
    client:
      minio:
        enable: true
        endpoint: http://127.0.0.1:9000/
        serverUrl: http://127.0.0.1:9000/
        defaultBucketName: cube
        accessKey: minioadmin
        secretKey: minioadmin
      local:
        enable: false
        endpoint: http://127.0.0.1:8001/
        defaultBucketName: cube
        readBlockSize: 8092
        writeBlockSize: 2048
